#!/bin/bash
set -u
IFS=$'\n\t'

VERBOSE=0
while [[ $# -gt 0 ]]; do
  case $1 in
    -h) echo "Usage: $(basename "$0") [ -v ]" && exit 0
      ;;
    -v) (( VERBOSE = VERBOSE + 1 ))
      ;;
    *) echo "Ignoring unknown argument '$1'.."
      ;;
  esac
  shift
done

TEST_INPUT=_testdata/160501_Grummus.txt
TEST_OUTPUT=_testdata/_test_$$.out
VERIFY_FILE=_testdata/expected.txt

trap 'rm $TEST_OUTPUT; exit' 1 2 3 15

python3 eqparsedpstables.py "$TEST_INPUT" > "$TEST_OUTPUT" 2>&1
[[ $? -ne 0 ]] && echo -e "FAIL\n# Script failed" && exit 1

diff -q "$VERIFY_FILE" "$TEST_OUTPUT" > /dev/null 2>&1
if [[ $? -eq 0 ]]; then
  [[ $VERBOSE -gt 0 ]] && echo PASS
  rm "$TEST_OUTPUT"
  exit 0
fi

echo FAIL

[[ $VERBOSE -eq 0 ]] && exit 1

ARGS=
[[ $VERBOSE -gt 1 ]] && ARGS=-wb

diff $ARGS "$VERIFY_FILE" "$TEST_OUTPUT"
exit 1
